use std::{
    fs::{self, OpenOptions},
    io::Write,
    path::{Path, PathBuf},
    sync::Arc,
};

use axum::{
    extract::{FromRef, Path as AxumPath, State},
    http::{header, HeaderName, HeaderValue, StatusCode},
    response::{IntoResponse, Response},
};
use rand::{rngs::OsRng, RngCore};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

#[cfg(test)]
use std::sync::atomic::{AtomicU64, Ordering};

use super::AppState;

const MODEL_AUDIO_MIME_TYPE: &str = "audio/mpeg";
const MODEL_AUDIO_MAX_BYTES: usize = 8 * 1024 * 1024;
const MODEL_AUDIO_DIRECTORY: &str = "model-audio";
const MODEL_AUDIO_RECEIPT_DIRECTORY: &str = "receipts";
const MODEL_AUDIO_URL_PREFIX: &str = "/assets/generated/model-audio";
const MODEL_AUDIO_TEMP_CREATE_ATTEMPTS: usize = 8;

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub(super) struct ModelAudioAsset {
    pub(super) asset_id: String,
    pub(super) url: String,
    pub(super) mime_type: String,
    pub(super) digest: String,
}

#[derive(Clone)]
pub(super) struct ModelAudioAssetState(Arc<PathBuf>);

impl FromRef<AppState> for ModelAudioAssetState {
    fn from_ref(state: &AppState) -> Self {
        Self(Arc::clone(&state.generated_asset_dir))
    }
}

/// Persists provider-generated MP3 bytes under their SHA-256 identity.
/// Repeating the same generation is idempotent; an existing object must still
/// pass framing and digest validation before it is reused.
pub(super) fn store_generated_model_audio(
    bytes: &[u8],
    generated_asset_dir: &Path,
) -> Result<ModelAudioAsset, String> {
    validate_model_audio_bytes(bytes)?;
    let digest = model_audio_digest(bytes);
    let path = model_audio_asset_path(generated_asset_dir, &digest);

    if path.exists() {
        let existing = read_validated_model_audio(generated_asset_dir, &digest)?;
        if existing != bytes {
            return Err("generated model-audio digest collision detected".to_string());
        }
    } else {
        atomic_persist_model_audio(&path, bytes)?;
        let persisted = read_validated_model_audio(generated_asset_dir, &digest)?;
        if persisted != bytes {
            return Err("generated model-audio persistence verification failed".to_string());
        }
    }

    Ok(model_audio_asset(&digest))
}

/// Recovers a previously generated asset for an immutable interaction receipt.
/// A present receipt is accepted only when both its digest mapping and target
/// asset still pass their complete validation.
pub(super) fn load_generated_model_audio_for_interaction(
    interaction_id: &str,
    generated_asset_dir: &Path,
) -> Result<Option<ModelAudioAsset>, String> {
    validate_model_audio_interaction_id(interaction_id)?;
    let receipt_path = model_audio_receipt_path(generated_asset_dir, interaction_id);
    let metadata = match fs::symlink_metadata(&receipt_path) {
        Ok(metadata) => metadata,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(error) => {
            return Err(format!(
                "generated model-audio interaction receipt metadata could not be read: {error}"
            ));
        }
    };
    if !metadata.file_type().is_file() || metadata.len() != 64 {
        return Err("generated model-audio interaction receipt metadata is invalid".to_string());
    }
    let digest_bytes = fs::read(receipt_path).map_err(|error| {
        format!("generated model-audio interaction receipt could not be read: {error}")
    })?;
    let digest = std::str::from_utf8(&digest_bytes)
        .map_err(|_| "generated model-audio interaction receipt was not UTF-8".to_string())?;
    validate_model_audio_asset_id(digest)?;
    read_validated_model_audio(generated_asset_dir, digest)?;
    Ok(Some(model_audio_asset(digest)))
}

/// Stores generated bytes and then publishes a no-replace interaction receipt.
/// If another worker already published a valid receipt, that first asset wins.
pub(super) fn store_generated_model_audio_for_interaction(
    interaction_id: &str,
    bytes: &[u8],
    generated_asset_dir: &Path,
) -> Result<ModelAudioAsset, String> {
    validate_model_audio_interaction_id(interaction_id)?;
    if let Some(asset) =
        load_generated_model_audio_for_interaction(interaction_id, generated_asset_dir)?
    {
        return Ok(asset);
    }

    let asset = store_generated_model_audio(bytes, generated_asset_dir)?;
    let receipt_path = model_audio_receipt_path(generated_asset_dir, interaction_id);
    if persist_model_audio_receipt(&receipt_path, &asset.digest)? {
        return Ok(asset);
    }
    load_generated_model_audio_for_interaction(interaction_id, generated_asset_dir)?.ok_or_else(
        || "generated model-audio interaction receipt disappeared during publication".to_string(),
    )
}

pub(super) async fn generated_model_audio_asset(
    State(ModelAudioAssetState(generated_asset_dir)): State<ModelAudioAssetState>,
    AxumPath(asset_file): AxumPath<String>,
) -> Response {
    let Some(asset_id) = asset_file.strip_suffix(".mp3") else {
        return StatusCode::NOT_FOUND.into_response();
    };
    if validate_model_audio_asset_id(asset_id).is_err() {
        return StatusCode::NOT_FOUND.into_response();
    }
    let asset_id = asset_id.to_string();
    let read_result = tokio::task::spawn_blocking(move || {
        read_validated_model_audio(generated_asset_dir.as_path(), &asset_id)
    })
    .await;
    let bytes = match read_result {
        Ok(Ok(bytes)) => bytes,
        Ok(Err(_)) => return StatusCode::NOT_FOUND.into_response(),
        Err(_) => return StatusCode::INTERNAL_SERVER_ERROR.into_response(),
    };

    let mut response = bytes.into_response();
    *response.status_mut() = StatusCode::OK;
    response.headers_mut().insert(
        header::CONTENT_TYPE,
        HeaderValue::from_static(MODEL_AUDIO_MIME_TYPE),
    );
    response.headers_mut().insert(
        header::CACHE_CONTROL,
        HeaderValue::from_static("public, max-age=31536000, immutable"),
    );
    response.headers_mut().insert(
        HeaderName::from_static("x-content-type-options"),
        HeaderValue::from_static("nosniff"),
    );
    response
}

fn read_validated_model_audio(root: &Path, asset_id: &str) -> Result<Vec<u8>, String> {
    validate_model_audio_asset_id(asset_id)?;
    let path = model_audio_asset_path(root, asset_id);
    let metadata = fs::symlink_metadata(&path)
        .map_err(|_| "generated model-audio asset was not found".to_string())?;
    if !metadata.file_type().is_file()
        || metadata.len() == 0
        || metadata.len() > MODEL_AUDIO_MAX_BYTES as u64
    {
        return Err("generated model-audio asset metadata is invalid".to_string());
    }
    let bytes = fs::read(path)
        .map_err(|error| format!("generated model-audio asset could not be read: {error}"))?;
    validate_model_audio_bytes(&bytes)?;
    if model_audio_digest(&bytes) != asset_id {
        return Err("generated model-audio asset failed digest verification".to_string());
    }
    Ok(bytes)
}

fn validate_model_audio_bytes(bytes: &[u8]) -> Result<(), String> {
    if bytes.is_empty() || bytes.len() > MODEL_AUDIO_MAX_BYTES {
        return Err("generated model-audio bytes were empty or exceeded 8 MiB".to_string());
    }
    if !has_plausible_id3_header(bytes) && !has_plausible_mpeg_frame_header(bytes) {
        return Err("generated model-audio bytes were not plausibly framed MP3".to_string());
    }
    Ok(())
}

fn has_plausible_id3_header(bytes: &[u8]) -> bool {
    if bytes.len() < 10
        || !bytes.starts_with(b"ID3")
        || !matches!(bytes[3], 2..=4)
        || bytes[4] == 0xff
        || !bytes[6..10].iter().all(|byte| byte & 0x80 == 0)
    {
        return false;
    }
    let tag_size = bytes[6..10]
        .iter()
        .fold(0_usize, |size, byte| (size << 7) | usize::from(*byte));
    let Some(frame_start) = 10_usize.checked_add(tag_size) else {
        return false;
    };
    bytes
        .get(frame_start..)
        .is_some_and(has_plausible_mpeg_frame_header)
}

fn has_plausible_mpeg_frame_header(bytes: &[u8]) -> bool {
    if bytes.len() < 4 || bytes[0] != 0xff || bytes[1] & 0xe0 != 0xe0 {
        return false;
    }
    let version = (bytes[1] >> 3) & 0x03;
    let layer = (bytes[1] >> 1) & 0x03;
    let bitrate = (bytes[2] >> 4) & 0x0f;
    let sample_rate = (bytes[2] >> 2) & 0x03;
    version != 0x01 && layer != 0 && !matches!(bitrate, 0 | 0x0f) && sample_rate != 0x03
}

fn validate_model_audio_asset_id(asset_id: &str) -> Result<(), String> {
    if !is_lowercase_sha256(asset_id) {
        return Err("generated model-audio asset id is invalid".to_string());
    }
    Ok(())
}

fn validate_model_audio_interaction_id(interaction_id: &str) -> Result<(), String> {
    if !is_lowercase_sha256(interaction_id) {
        return Err("generated model-audio interaction id is invalid".to_string());
    }
    Ok(())
}

fn is_lowercase_sha256(value: &str) -> bool {
    value.len() == 64
        && value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

fn model_audio_digest(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn model_audio_url(asset_id: &str) -> String {
    format!("{MODEL_AUDIO_URL_PREFIX}/{asset_id}.mp3")
}

fn model_audio_asset(digest: &str) -> ModelAudioAsset {
    ModelAudioAsset {
        asset_id: digest.to_string(),
        url: model_audio_url(digest),
        mime_type: MODEL_AUDIO_MIME_TYPE.to_string(),
        digest: digest.to_string(),
    }
}

fn model_audio_asset_dir(root: &Path) -> PathBuf {
    root.join(MODEL_AUDIO_DIRECTORY)
}

fn model_audio_asset_path(root: &Path, asset_id: &str) -> PathBuf {
    model_audio_asset_dir(root).join(format!("{asset_id}.mp3"))
}

fn model_audio_receipt_dir(root: &Path) -> PathBuf {
    model_audio_asset_dir(root).join(MODEL_AUDIO_RECEIPT_DIRECTORY)
}

fn model_audio_receipt_path(root: &Path, interaction_id: &str) -> PathBuf {
    model_audio_receipt_dir(root).join(format!("{interaction_id}.sha256"))
}

fn atomic_persist_model_audio(path: &Path, bytes: &[u8]) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| "generated model-audio storage path has no parent".to_string())?;
    fs::create_dir_all(parent).map_err(|error| {
        format!("generated model-audio directory could not be created: {error}")
    })?;
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| "generated model-audio storage filename is invalid".to_string())?;
    let (temporary, mut file) = create_model_audio_temporary_file(parent, file_name)?;

    let write_result = (|| -> Result<(), String> {
        file.write_all(bytes).map_err(|error| {
            format!("generated model-audio temporary file could not be written: {error}")
        })?;
        file.sync_all().map_err(|error| {
            format!("generated model-audio temporary file could not be synced: {error}")
        })?;
        drop(file);
        fs::rename(&temporary, path).map_err(|error| {
            format!("generated model-audio asset could not be published: {error}")
        })?;
        sync_model_audio_directory(parent)
    })();
    if write_result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    write_result
}

fn persist_model_audio_receipt(path: &Path, digest: &str) -> Result<bool, String> {
    let parent = path
        .parent()
        .ok_or_else(|| "generated model-audio receipt path has no parent".to_string())?;
    fs::create_dir_all(parent).map_err(|error| {
        format!("generated model-audio receipt directory could not be created: {error}")
    })?;
    if let Some(receipt_directory_parent) = parent.parent() {
        sync_model_audio_directory(receipt_directory_parent)?;
    }
    let file_name = path
        .file_name()
        .and_then(|value| value.to_str())
        .ok_or_else(|| "generated model-audio receipt filename is invalid".to_string())?;
    let (temporary, mut file) = create_model_audio_temporary_file(parent, file_name)?;
    let write_result = (|| -> Result<(), String> {
        file.write_all(digest.as_bytes()).map_err(|error| {
            format!("generated model-audio temporary receipt could not be written: {error}")
        })?;
        file.sync_all().map_err(|error| {
            format!("generated model-audio temporary receipt could not be synced: {error}")
        })
    })();
    drop(file);
    if let Err(error) = write_result {
        let _ = fs::remove_file(&temporary);
        return Err(error);
    }

    let published = match fs::hard_link(&temporary, path) {
        Ok(()) => true,
        Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => false,
        Err(error) => {
            let _ = fs::remove_file(&temporary);
            return Err(format!(
                "generated model-audio interaction receipt could not be published: {error}"
            ));
        }
    };
    fs::remove_file(&temporary).map_err(|error| {
        format!("generated model-audio temporary receipt could not be removed: {error}")
    })?;
    sync_model_audio_directory(parent)?;
    Ok(published)
}

fn sync_model_audio_directory(directory: &Path) -> Result<(), String> {
    let directory = fs::File::open(directory).map_err(|error| {
        format!("generated model-audio directory could not be opened for sync: {error}")
    })?;
    directory
        .sync_all()
        .map_err(|error| format!("generated model-audio directory could not be synced: {error}"))
}

fn create_model_audio_temporary_file(
    parent: &Path,
    file_name: &str,
) -> Result<(PathBuf, fs::File), String> {
    let mut rng = OsRng;
    for _ in 0..MODEL_AUDIO_TEMP_CREATE_ATTEMPTS {
        let mut nonce = [0_u8; 16];
        rng.try_fill_bytes(&mut nonce).map_err(|error| {
            format!("generated model-audio temporary filename randomness failed: {error}")
        })?;
        let temporary = parent.join(format!(
            ".{file_name}.tmp-{:032x}",
            u128::from_be_bytes(nonce)
        ));
        match OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&temporary)
        {
            Ok(file) => return Ok((temporary, file)),
            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,
            Err(error) => {
                return Err(format!(
                    "generated model-audio temporary file could not be created: {error}"
                ));
            }
        }
    }
    Err("generated model-audio unique temporary file could not be created".to_string())
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::body::to_bytes;

    static TEST_DIRECTORY_SEQUENCE: AtomicU64 = AtomicU64::new(0);

    fn test_root(label: &str) -> PathBuf {
        let sequence = TEST_DIRECTORY_SEQUENCE.fetch_add(1, Ordering::Relaxed);
        std::env::temp_dir().join(format!(
            "cosyworld-model-audio-{label}-{}-{sequence}",
            std::process::id()
        ))
    }

    fn id3_mp3() -> Vec<u8> {
        b"ID3\x04\x00\x00\x00\x00\x00\x04test\xff\xfb\x90\x64frame-data".to_vec()
    }

    #[test]
    fn generated_mp3_is_content_addressed_and_idempotently_persisted() {
        let root = test_root("persist");
        let bytes = id3_mp3();
        let expected_digest = model_audio_digest(&bytes);

        let first = store_generated_model_audio(&bytes, &root).expect("store generated MP3");
        let second =
            store_generated_model_audio(&bytes, &root).expect("reuse identical generated MP3");

        assert_eq!(first, second);
        assert_eq!(first.asset_id, expected_digest);
        assert_eq!(first.digest, expected_digest);
        assert_eq!(first.mime_type, "audio/mpeg");
        assert_eq!(
            first.url,
            format!("/assets/generated/model-audio/{}.mp3", first.asset_id)
        );
        assert_eq!(
            fs::read(model_audio_asset_path(&root, &first.asset_id))
                .expect("read persisted generated MP3"),
            bytes
        );
        fs::remove_dir_all(root).expect("remove model-audio persistence fixture");
    }

    #[test]
    fn empty_oversized_and_unframed_audio_is_rejected_before_persistence() {
        let root = test_root("invalid");
        for bytes in [
            Vec::new(),
            vec![0_u8; MODEL_AUDIO_MAX_BYTES + 1],
            b"ID3too-short".to_vec(),
            b"ID3\x04\x00\x00\x00\x00\x00\x04test".to_vec(),
            b"ID3\x04\x00\x00\x00\x00\x00\x7ftiny\xff\xfb\x90\x64frame-data".to_vec(),
            b"not-an-mp3".to_vec(),
        ] {
            assert!(store_generated_model_audio(&bytes, &root).is_err());
        }
        assert!(!model_audio_asset_dir(&root).exists());
    }

    #[test]
    fn interaction_receipt_recovers_the_first_valid_generated_asset() {
        let root = test_root("receipt");
        let interaction_id = model_audio_digest(b"model-audio-interaction");
        let first_bytes = id3_mp3();
        let second_bytes = b"\xff\xfb\x90\x64different-frame-data";

        assert_eq!(
            load_generated_model_audio_for_interaction(&interaction_id, &root)
                .expect("load absent model-audio receipt"),
            None
        );
        let first =
            store_generated_model_audio_for_interaction(&interaction_id, &first_bytes, &root)
                .expect("store first interaction audio");
        let recovered =
            store_generated_model_audio_for_interaction(&interaction_id, second_bytes, &root)
                .expect("recover first interaction audio");

        assert_eq!(recovered, first);
        assert_eq!(
            load_generated_model_audio_for_interaction(&interaction_id, &root)
                .expect("load persisted model-audio receipt"),
            Some(first.clone())
        );
        assert_eq!(
            fs::read(model_audio_receipt_path(&root, &interaction_id))
                .expect("read model-audio receipt"),
            first.digest.as_bytes()
        );
        assert!(!model_audio_asset_path(&root, &model_audio_digest(second_bytes)).exists());
        assert_eq!(
            fs::read_dir(model_audio_receipt_dir(&root))
                .expect("read model-audio receipt directory")
                .count(),
            1
        );
        fs::remove_dir_all(root).expect("remove model-audio receipt fixture");
    }

    #[test]
    fn interaction_receipt_requires_a_lowercase_sha256_interaction_id() {
        let root = test_root("invalid-receipt-id");
        let uppercase = "A".repeat(64);
        let traversal = format!("{}../", "a".repeat(61));

        for interaction_id in ["", uppercase.as_str(), traversal.as_str()] {
            assert!(load_generated_model_audio_for_interaction(interaction_id, &root).is_err());
            assert!(
                store_generated_model_audio_for_interaction(interaction_id, &id3_mp3(), &root)
                    .is_err()
            );
        }
        assert!(!model_audio_asset_dir(&root).exists());
    }

    #[test]
    fn malformed_or_orphaned_interaction_receipt_is_rejected() {
        let root = test_root("invalid-receipt");
        let interaction_id = model_audio_digest(b"invalid-receipt-interaction");
        let receipt_path = model_audio_receipt_path(&root, &interaction_id);
        fs::create_dir_all(receipt_path.parent().expect("receipt parent"))
            .expect("create receipt fixture directory");

        fs::write(&receipt_path, "g".repeat(64)).expect("write malformed receipt fixture");
        assert!(load_generated_model_audio_for_interaction(&interaction_id, &root).is_err());

        fs::write(&receipt_path, model_audio_digest(b"missing-asset"))
            .expect("write orphaned receipt fixture");
        assert!(load_generated_model_audio_for_interaction(&interaction_id, &root).is_err());

        fs::remove_dir_all(root).expect("remove invalid receipt fixture");
    }

    #[test]
    fn an_mpeg_frame_sync_header_is_accepted() {
        let root = test_root("frame-sync");
        let bytes = b"\xff\xfb\x90\x64frame-data";

        let asset =
            store_generated_model_audio(bytes, &root).expect("store frame-synced generated MP3");

        assert_eq!(asset.asset_id, model_audio_digest(bytes));
        fs::remove_dir_all(root).expect("remove frame-sync fixture");
    }

    #[tokio::test]
    async fn handler_serves_only_digest_checked_mp3_with_immutable_headers() {
        let root = test_root("handler");
        let bytes = id3_mp3();
        let asset =
            store_generated_model_audio(&bytes, &root).expect("store handler generated MP3");
        let state = ModelAudioAssetState(Arc::new(root.clone()));

        let response = generated_model_audio_asset(
            State(state.clone()),
            AxumPath(format!("{}.mp3", asset.asset_id)),
        )
        .await;

        assert_eq!(response.status(), StatusCode::OK);
        assert_eq!(
            response.headers().get(header::CONTENT_TYPE),
            Some(&HeaderValue::from_static("audio/mpeg"))
        );
        assert_eq!(
            response.headers().get(header::CACHE_CONTROL),
            Some(&HeaderValue::from_static(
                "public, max-age=31536000, immutable"
            ))
        );
        assert_eq!(
            response.headers().get("x-content-type-options"),
            Some(&HeaderValue::from_static("nosniff"))
        );
        let served = to_bytes(response.into_body(), MODEL_AUDIO_MAX_BYTES)
            .await
            .expect("read generated model-audio response");
        assert_eq!(served.as_ref(), bytes.as_slice());

        let uppercase = generated_model_audio_asset(
            State(state.clone()),
            AxumPath(format!("{}.mp3", asset.asset_id.to_ascii_uppercase())),
        )
        .await;
        assert_eq!(uppercase.status(), StatusCode::NOT_FOUND);

        fs::write(
            model_audio_asset_path(&root, &asset.asset_id),
            b"\xff\xfb\x90\x64different-frame-data",
        )
        .expect("tamper generated MP3 fixture");
        let tampered =
            generated_model_audio_asset(State(state), AxumPath(format!("{}.mp3", asset.asset_id)))
                .await;
        assert_eq!(tampered.status(), StatusCode::NOT_FOUND);

        fs::remove_dir_all(root).expect("remove model-audio handler fixture");
    }
}
