/**
 * Copyright (c) 2019-2024 Cenetex Inc.
 * Licensed under the MIT License.
 *
 * Gallery API
 * Serves images and videos generated by the system.
 */

import { Router } from 'express';
import { ObjectId } from 'mongodb';

/**
 * @param {import('mongodb').Db} db
 * @param {Object} services
 */
export default function galleryRoutes(db, services = {}) {
  const router = Router();
  const logger = services.logger || console;

  /**
   * GET /api/gallery
   * List all media (images and videos) with filtering
   */
  router.get('/', async (req, res) => {
    try {
      const limit = Math.min(parseInt(req.query.limit) || 50, 200);
      const offset = parseInt(req.query.offset) || 0;
      const { type, category, purpose, source, search } = req.query;

      // Build filter for generated_images collection
      const filter = {};
      if (category) filter.category = category;
      if (purpose) filter.purpose = purpose;
      if (source) filter.source = source;
      if (search) {
        filter.$or = [
          { prompt: { $regex: search, $options: 'i' } },
          { tags: { $regex: search, $options: 'i' } },
        ];
      }

      // Fetch images
      let images = [];
      let videos = [];
      
      if (!type || type === 'image' || type === 'all') {
        const imageDocs = await db.collection('generated_images')
          .find(filter)
          .sort({ createdAt: -1 })
          .skip(offset)
          .limit(limit)
          .toArray();
        
        images = imageDocs.map(doc => ({
          _id: doc._id,
          type: 'image',
          url: doc.imageUrl,
          thumbnailUrl: doc.thumbnailUrl || doc.imageUrl,
          prompt: doc.prompt,
          purpose: doc.purpose,
          category: doc.category,
          tags: doc.tags || [],
          metadata: doc.metadata || {},
          source: doc.source,
          usageCount: doc.usageCount || 0,
          createdAt: doc.createdAt,
        }));
      }

      if (!type || type === 'video' || type === 'all') {
        const videoFilter = { status: 'completed' };
        if (search) {
          videoFilter.$or = [
            { prompt: { $regex: search, $options: 'i' } },
            { 'metadata.purpose': { $regex: search, $options: 'i' } },
          ];
        }

        const videoDocs = await db.collection('video_jobs')
          .find(videoFilter)
          .sort({ completedAt: -1, createdAt: -1 })
          .skip(type === 'video' ? offset : 0)
          .limit(type === 'video' ? limit : Math.floor(limit / 2))
          .toArray();

        videos = videoDocs.map(doc => ({
          _id: doc._id,
          type: 'video',
          url: doc.videoUrl || doc.outputUrl,
          thumbnailUrl: doc.thumbnailUrl || doc.referenceImageUrl,
          prompt: doc.prompt,
          purpose: doc.metadata?.purpose || 'video',
          category: doc.metadata?.category || 'general',
          tags: doc.metadata?.tags || [],
          metadata: doc.metadata || {},
          source: doc.source || 'veo',
          duration: doc.duration,
          createdAt: doc.createdAt,
          completedAt: doc.completedAt,
        }));
      }

      // Merge and sort by date
      let media = [...images, ...videos];
      if (type === 'all' || !type) {
        media.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));
        media = media.slice(0, limit);
      }

      const totalImages = type === 'video' ? 0 : await db.collection('generated_images').countDocuments(filter);
      const totalVideos = type === 'image' ? 0 : await db.collection('video_jobs').countDocuments({ status: 'completed' });

      res.json({
        data: media,
        total: totalImages + totalVideos,
        images: totalImages,
        videos: totalVideos,
        limit,
        offset,
      });
    } catch (e) {
      logger.error('[gallery] GET / failed:', e);
      res.status(500).json({ error: 'Internal server error' });
    }
  });

  /**
   * GET /api/gallery/images
   * List only generated images
   */
  router.get('/images', async (req, res) => {
    try {
      const limit = Math.min(parseInt(req.query.limit) || 50, 200);
      const offset = parseInt(req.query.offset) || 0;
      const { category, purpose, source, tags, search } = req.query;

      const filter = {};
      if (category) filter.category = category;
      if (purpose) filter.purpose = purpose;
      if (source) filter.source = source;
      if (tags) {
        const tagList = tags.split(',').map(t => t.trim());
        filter.tags = { $in: tagList };
      }
      if (search) {
        filter.$or = [
          { prompt: { $regex: search, $options: 'i' } },
          { tags: { $regex: search, $options: 'i' } },
          { keywords: { $regex: search, $options: 'i' } },
        ];
      }

      const [docs, total] = await Promise.all([
        db.collection('generated_images')
          .find(filter)
          .sort({ createdAt: -1 })
          .skip(offset)
          .limit(limit)
          .toArray(),
        db.collection('generated_images').countDocuments(filter),
      ]);

      res.json({
        data: docs.map(doc => ({
          _id: doc._id,
          url: doc.imageUrl,
          thumbnailUrl: doc.thumbnailUrl || doc.imageUrl,
          prompt: doc.prompt,
          purpose: doc.purpose,
          category: doc.category,
          tags: doc.tags || [],
          metadata: doc.metadata || {},
          source: doc.source,
          usageCount: doc.usageCount || 0,
          createdAt: doc.createdAt,
        })),
        total,
        limit,
        offset,
      });
    } catch (e) {
      logger.error('[gallery] GET /images failed:', e);
      res.status(500).json({ error: 'Internal server error' });
    }
  });

  /**
   * GET /api/gallery/videos
   * List only generated videos
   */
  router.get('/videos', async (req, res) => {
    try {
      const limit = Math.min(parseInt(req.query.limit) || 50, 200);
      const offset = parseInt(req.query.offset) || 0;
      const { status, source, search } = req.query;

      const filter = {};
      // Default to completed videos unless explicitly requesting other statuses
      filter.status = status || 'completed';
      if (source) filter.source = source;
      if (search) {
        filter.$or = [
          { prompt: { $regex: search, $options: 'i' } },
        ];
      }

      const [docs, total] = await Promise.all([
        db.collection('video_jobs')
          .find(filter)
          .sort({ completedAt: -1, createdAt: -1 })
          .skip(offset)
          .limit(limit)
          .toArray(),
        db.collection('video_jobs').countDocuments(filter),
      ]);

      res.json({
        data: docs.map(doc => ({
          _id: doc._id,
          url: doc.videoUrl || doc.outputUrl,
          thumbnailUrl: doc.thumbnailUrl || doc.referenceImageUrl,
          prompt: doc.prompt,
          status: doc.status,
          purpose: doc.metadata?.purpose,
          metadata: doc.metadata || {},
          source: doc.source || 'veo',
          duration: doc.duration,
          createdAt: doc.createdAt,
          completedAt: doc.completedAt,
        })),
        total,
        limit,
        offset,
      });
    } catch (e) {
      logger.error('[gallery] GET /videos failed:', e);
      res.status(500).json({ error: 'Internal server error' });
    }
  });

  /**
   * GET /api/gallery/images/:id
   * Get a single image by ID
   */
  router.get('/images/:id', async (req, res) => {
    try {
      let id;
      try { id = new ObjectId(req.params.id); } catch {
        return res.status(400).json({ error: 'Invalid ID format' });
      }

      const doc = await db.collection('generated_images').findOne({ _id: id });
      if (!doc) {
        return res.status(404).json({ error: 'Image not found' });
      }

      // Increment usage count
      await db.collection('generated_images').updateOne(
        { _id: id },
        { $inc: { usageCount: 1 }, $set: { lastUsedAt: new Date() } }
      );

      res.json({
        _id: doc._id,
        url: doc.imageUrl,
        thumbnailUrl: doc.thumbnailUrl || doc.imageUrl,
        prompt: doc.prompt,
        promptHash: doc.promptHash,
        purpose: doc.purpose,
        category: doc.category,
        tags: doc.tags || [],
        keywords: doc.keywords || [],
        metadata: doc.metadata || {},
        source: doc.source,
        cost: doc.cost,
        usageCount: (doc.usageCount || 0) + 1,
        createdAt: doc.createdAt,
        lastUsedAt: new Date(),
      });
    } catch (e) {
      logger.error('[gallery] GET /images/:id failed:', e);
      res.status(500).json({ error: 'Internal server error' });
    }
  });

  /**
   * GET /api/gallery/videos/:id
   * Get a single video by ID
   */
  router.get('/videos/:id', async (req, res) => {
    try {
      let id;
      try { id = new ObjectId(req.params.id); } catch {
        return res.status(400).json({ error: 'Invalid ID format' });
      }

      const doc = await db.collection('video_jobs').findOne({ _id: id });
      if (!doc) {
        return res.status(404).json({ error: 'Video not found' });
      }

      res.json({
        _id: doc._id,
        url: doc.videoUrl || doc.outputUrl,
        thumbnailUrl: doc.thumbnailUrl || doc.referenceImageUrl,
        prompt: doc.prompt,
        enhancedPrompt: doc.enhancedPrompt,
        status: doc.status,
        purpose: doc.metadata?.purpose,
        metadata: doc.metadata || {},
        source: doc.source || 'veo',
        duration: doc.duration,
        aspectRatio: doc.aspectRatio,
        createdAt: doc.createdAt,
        completedAt: doc.completedAt,
        error: doc.error,
      });
    } catch (e) {
      logger.error('[gallery] GET /videos/:id failed:', e);
      res.status(500).json({ error: 'Internal server error' });
    }
  });

  /**
   * GET /api/gallery/categories
   * Get list of available categories and purposes
   */
  router.get('/categories', async (req, res) => {
    try {
      const [categories, purposes, sources] = await Promise.all([
        db.collection('generated_images').distinct('category'),
        db.collection('generated_images').distinct('purpose'),
        db.collection('generated_images').distinct('source'),
      ]);

      res.json({
        categories: categories.filter(Boolean).sort(),
        purposes: purposes.filter(Boolean).sort(),
        sources: sources.filter(Boolean).sort(),
      });
    } catch (e) {
      logger.error('[gallery] GET /categories failed:', e);
      res.status(500).json({ error: 'Internal server error' });
    }
  });

  /**
   * GET /api/gallery/stats
   * Get gallery statistics
   */
  router.get('/stats', async (req, res) => {
    try {
      const [
        totalImages,
        totalVideos,
        completedVideos,
        pendingVideos,
        categoryCounts,
        purposeCounts,
      ] = await Promise.all([
        db.collection('generated_images').countDocuments(),
        db.collection('video_jobs').countDocuments(),
        db.collection('video_jobs').countDocuments({ status: 'completed' }),
        db.collection('video_jobs').countDocuments({ status: { $in: ['pending', 'processing'] } }),
        db.collection('generated_images').aggregate([
          { $group: { _id: '$category', count: { $sum: 1 } } },
          { $sort: { count: -1 } },
        ]).toArray(),
        db.collection('generated_images').aggregate([
          { $group: { _id: '$purpose', count: { $sum: 1 } } },
          { $sort: { count: -1 } },
        ]).toArray(),
      ]);

      res.json({
        images: {
          total: totalImages,
          byCategory: Object.fromEntries(categoryCounts.map(c => [c._id || 'unknown', c.count])),
          byPurpose: Object.fromEntries(purposeCounts.map(p => [p._id || 'unknown', p.count])),
        },
        videos: {
          total: totalVideos,
          completed: completedVideos,
          pending: pendingVideos,
        },
      });
    } catch (e) {
      logger.error('[gallery] GET /stats failed:', e);
      res.status(500).json({ error: 'Internal server error' });
    }
  });

  /**
   * GET /api/gallery/recent
   * Get most recent media across all types
   */
  router.get('/recent', async (req, res) => {
    try {
      const limit = Math.min(parseInt(req.query.limit) || 20, 100);

      const [recentImages, recentVideos] = await Promise.all([
        db.collection('generated_images')
          .find({})
          .sort({ createdAt: -1 })
          .limit(limit)
          .toArray(),
        db.collection('video_jobs')
          .find({ status: 'completed' })
          .sort({ completedAt: -1 })
          .limit(limit)
          .toArray(),
      ]);

      const media = [
        ...recentImages.map(doc => ({
          _id: doc._id,
          type: 'image',
          url: doc.imageUrl,
          thumbnailUrl: doc.thumbnailUrl || doc.imageUrl,
          prompt: doc.prompt?.slice(0, 200),
          category: doc.category,
          createdAt: doc.createdAt,
        })),
        ...recentVideos.map(doc => ({
          _id: doc._id,
          type: 'video',
          url: doc.videoUrl || doc.outputUrl,
          thumbnailUrl: doc.thumbnailUrl || doc.referenceImageUrl,
          prompt: doc.prompt?.slice(0, 200),
          category: doc.metadata?.category,
          createdAt: doc.completedAt || doc.createdAt,
        })),
      ];

      // Sort by date and take top N
      media.sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt));

      res.json({
        data: media.slice(0, limit),
      });
    } catch (e) {
      logger.error('[gallery] GET /recent failed:', e);
      res.status(500).json({ error: 'Internal server error' });
    }
  });

  return router;
}
